# Docker Compose file for dependencies needed to test library
version: '3'
services:
  # An nginx web server hosting static content in resources/static directory.
  static-file-server:
    image: nginx:alpine
    ports:
      - 8001:80
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/static:/var/www:ro